### ISSUE TITLE
unclear "How to use" section

### ISSUE THREAD

**Issue by picalof241** [meik97/XSpotify#1]
- Download XSpotify
This step i click green download button on github

- Place all files into your Spotify directory (C:\Users<USERNAME>\AppData\Roaming\Spotify)
Then this step i'm not really sure, like copy all files and folder like `.gitignore`, `LICENSE`, `README.md`, `XSpotifyHelper` into `Roaming\Spotify` folder ???

- Start XSpotify
How i suppose to open it, in youtube video you have an .exe file but when i download in step 1, i can't find it

**Comment by meik97** [comment]
Binaries were not uploaded until now.

You can download them here: https://github.com/meik97/XSpotify/releases

Thank you for the reminder!
