### ISSUE TITLE
Add tags to songs

### ISSUE THREAD

**Issue by vinanrra** [meik97/XSpotify#10]
It could be good to add:

Artist and Album to files instead of only have the name of the song.

Could be like this:

[Artist] - [Album] - [Song].ogg

**Comment by OwenHunter** [comment]
+1

**Comment by GilbertoTorres** [comment]
+1

**Comment by 25khattab** [comment]
+1

**Comment by meik97** [comment]
Tags are included in 1.3
They won't be added into the file name for now
