### ISSUE TITLE
The system cannot execute the specified program.

### ISSUE THREAD

**Issue by MihailCosmin** [meik97/XSpotify#13]
I am getting this error: "The system cannot execute the specified program."

Does XSpotify work only with the "program" version of the Spotify ? Or also with the Microsoft Store "app" version ?

**Comment by meik97** [comment]
It does not work with the store app.

**Comment by MihailCosmin** [comment]
Found a way to "install" the "program": installed it first in a Virtualbox, then just copied the "C:\Users\ **USER** \AppData\Roaming\Spotify" folder to my real Windows.
