### ISSUE TITLE
System Error when trying to run  

### ISSUE THREAD

**Issue by WendyWahnsinn** [meik97/XSpotify#16]
Hi, 

I tried to use it but when I start the .exe i get the following error message (translated from german) : 
"System Error - the execution of the code could not be proceded, because VCRUNTIME140.dll could not be found. The Problem could possibly be fixed through re-installation of the program" 

Any idea how to fix that?

**Comment by MihailCosmin** [comment]
It says in the Requirements List:

> You need Microsoft's Visual C++ Redistributable Runtimes installed.
