### ISSUE TITLE
Crashes immediately after starting up

### ISSUE THREAD

**Issue by umstek** [meik97/XSpotify#19]
Spotify and XSpotify both crash as soon as XSpotify is started. 
This happens before playing anything (not #3), and I used a free account (not #8).

**Comment by fortender** [comment]
Spotify version? The README states that the current release is tested for 
> 1.1.24.91.g4ca6d5eb (15.01.2020)

**Comment by umstek** [comment]
The latest 1.1.25.559. :/

**Comment by umstek** [comment]
Installed 1.1.24.91 and followed instructions here https://github.com/meik97/XSpotify/issues/3#issuecomment-577991801
