### ISSUE TITLE
False positives from multiple antivirus software

### ISSUE THREAD

**Issue by c0sMx** [meik97/XSpotify#20]
http://r.virscan.org/language/zh-cn/report/b2794cbc0e81ff858d671c73731205d3

https://www.virustotal.com/gui/file/e93e40a311557162ec3b7fc9a0410974287b53f4b2f43f7013bece1703c3777e/detection

https://virusscan.jotti.org/zh-CN/filescanjob/65boc9ry8z

**Comment by fortender** [comment]
Why did you open an issue for that? This is already well-known and has been discussed already. What do you aim to achieve with this issue?

**Comment by c0sMx** [comment]
> Why did you open an issue for that? This is already well-known and has been discussed already. What do you aim to achieve with this issue?

I will uninstall my antivirus software
