### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by xbbdc** [meik97/XSpotify#26]
OS: Win10 2004 19041.84
Spotify: 1.1.24.91

I spent several hours last night trying to get this to work. First I began by not following directions and started by using the latest version of Spotify (1.1.26.501) and copied the XSpotify folder to %appdata%\spotify. I then realized I had to copy the files inside the folder not the entire folder. Crashed a lot. Then I some of the directions and used the link for the Visual C++ AiO package and rebooted. Still crashing. Then read the open issue about the crashing and realized the readme page said it was tested on version 1.1.25.559. This version is impossible to find. Does not exist online. Someone rar'd their Spotify folder and uploaded to Mega as one of the comments here somewhere and found it was version 1.1.24.91. I thought I was in luck. Still crashing. Finally got XSpotify and player stable with switching playlists and songs but the cursor just blinks in XSpotify window. It doesn't pick anything up and nothing happens.

@meik97 Please post full Spotify version that we can download on which you test to help make this easier imo.

**Comment by meik97** [comment]
Hello @xbbdc,

you can find the right Spotify version in the download section of my discord server.

Go to #downloads:
https://discord.gg/EByRp27
