### ISSUE TITLE
Podcast download

### ISSUE THREAD

**Issue by herrsunchess** [meik97/XSpotify#28]
Hi there,
So apparently XSpotify crashes when you try to download podcasts. This happens when you immediately try to download a podcast. If you play a normal song first, you can download a podcast and it will be tagged as the song youve heard before.
Steps to reproduce:
_Open app_ -> _Play podcast_ -> _dl_ -> _App crashs_
_Open app_ -> _Play song_ -> _Play podcast_ -> _dl_ -> _Downloaded podcast & tagged as song_
I hope it is fixable but nevertheless thx for your app.

**Comment by meik97** [comment]
Hello @herrsunchess,

Podcasts are currently not supported by XSpotify.
