### ISSUE TITLE
use heap allocation functions instead of the static arrays

### ISSUE THREAD

**Issue by heape** [meik97/XSpotify#29]
https://github.com/meik97/XSpotify/blob/master/XSpotify/Modules/XPatchDownloads.hpp#L35
```
35:	unsigned char rawDecryptedData[50000000];
36:	unsigned char outputData[50000000];
```
to deal with big audio data, should use heap allocation functions.
for example, malloc, calloc or whatever.

note: I am BAKADESU :D

**Comment by meik97** [comment]
Will be fixed in future releases.

**Comment by meik97** [comment]
Fixed in the dev branch and will be added to the master branch in the next release.
