### ISSUE TITLE
Spotify Crashed after hint [download finished]

### ISSUE THREAD

**Issue by hyang57** [meik97/XSpotify#30]
OS : Win 10 1903
Client: 1.1.27.472(Spotify), 1.5(XSpotify)
Account: Spotify Premium

How to replicate this issue:

1. Switch 1-2 songs then  type "dl" command.

2. Wait for a long time. (Because the download speed is limited at ~500KB/s, however, this is the only PC I could find now.)

3. Sometimes XSpotify would crash before the hint "[download finished]", sometimes XSpotify crashes right after "[download finished]" or the next time I tried to type "dl" command. 

Then I could find the cover of the song I tried to download and a ~3MB .ogg file in Xsongs folder, but the .ogg file is broken.

**Comment by hyang57** [comment]
> What XSpotify version are you using ?
> 
> 1.27... is not supported by XSpotify, make sure you are using XSpotify v1.5

Sorry, I mean I'm using Spotify 1.1.27.472 (03-05-2020).And I'm using XSpotify v1.5.

Please do not hesitate to ask me if you need any further information.

**Comment by meik97** [comment]
Do you have any antivirus installed ?

XSpotify currently does not check if everything is set up corretly to run without any issues.
As stated in issue #27, make sure the folder "XSongs" is present in your Spotify directory.
Otherwise XSpotify will end in a crash after downloading a song.
