### ISSUE TITLE
Automation?

### ISSUE THREAD

**Issue by jonathandanforth** [meik97/XSpotify#31]
First off, thank you for this. This isn't an "issue" but I didn't know a better place to make the request.

Is there a way to automate the process? Could we start an album and just automatically "dl\x0d" into the window with each new track? Or feed the app a playlist URI to pull down?

**Comment by meik97** [comment]
Yes there is a way. It was enabled back in the first releases. Unfortunately it caused alot more crashes than now and was therefore disabled.

I will probably make a test build where people can test a feature like this, but for now you need to download every song by yourself.

**Comment by jonathandanforth** [comment]
Good to know, thanks! I was thinking that I might be able to figure out a workaround using AutoHotkey but I've never used that before and need to figure it out. Maybe even something as simple as monitoring for the "Type 'dl' to download..." string to appear in the console and then use AHK to type just that...
