### ISSUE TITLE
Automated setup

### ISSUE THREAD

**Issue by maximousblk** [meik97/XSpotify#34]
Mentioned in #32 

It was easy enough to get this up and running but a set of installer, updater and uninstaller would make it nicer to setup and also reduce the chances of human errors.

A simple batch file that checks if a backup exists and if not, safely renames the original `spotify.exe` to `spotify.exe.bak` and copies the files to the destinations.

Updater would replace all the files with the new ones except `spotify.exe.bak`.

Uninstaller would delete all the xSpotify files and rename `spotify.exe.bak` to `spotify.exe` again.

**Comment by meik97** [comment]
Automated setup is not planned for now.
It will be done when higher priority issues are solved and the project itself is ready to get one.
