### ISSUE TITLE
Better terminal controls

### ISSUE THREAD

**Issue by maximousblk** [meik97/XSpotify#36]
Mentioned in #32 

Not many people like having a terminal telling you only the track id of the currently playing song. something similar to the following would be way more appealing your non geek fellows and the terminal gods alike.

```txt
        _____             _   _  __
       / ____|           | | (_)/ _|
 __  _| (___  _ __   ___ | |_ _| |_ _   _
 \ \/ /\___ \| '_ \ / _ \| __| |  _| | | |
  >  < ____) | |_) | (_) | |_| | | | |_| |
 /_/\_\_____/| .__/ \___/ \__|_|_|  \__, |
             | |                     __/ |
             |_|                    |___/   v2.0

Now Playing
 # Track: Constellation
 # Album: Constellation
 # Artists: Win and Woo
 # Id: 3b71h4RqnMZ4d7UmTOwA0m

xSpotify> help

xSpotify v2.0.0 Stable

repo: https://github.com/meik97/xspotify

Options:

    dl    - Download current song
    next  - Next Song
    prev  - Previous Song
    paws  - Pause the player
    cls   - Clear all outputs
    help  - This help menu
```

It would be awesome if we could control music right from the terminal.

**Comment by meik97** [comment]
The cosole window will most likely find its end soon so there is no point for more commands.

I am aiming to keep all features within the original Spotify window
