### ISSUE TITLE
Crashes directly after starting up Spotify

### ISSUE THREAD

**Issue by bascurtiz** [meik97/XSpotify#8]
Similar but different to Issue #3 .
I don't have to play anything and XSpotify crashes already.

See: https://youtu.be/YQKUiWPEx-g

Can you implement a method to create a log file?

What I tried:
- Read-only  disabled on the appdata/roaming/spotify  folder.
- Updated Spotify to the latest.
- Right-click Run as Admin on Xspotify.
- Still crashes Xspotify after opening up Spotify (which does seem to work).
- Win10 1909.

Link to my Spotify folder (incl. Xspotify) so you might be able to debug/compare it to yours:
https://mega.nz/#!YEAjSAID!YMhku6R9Ho5wfOI__gQBByGqmvu3lnZ0WnSgxHco5Lg

**Comment by Essasetic** [comment]
I had the same issue. Making a free account and using it fixed it for me. Premium accounts don't work with this program for some reason.

**Comment by bascurtiz** [comment]
@Essasetic 
Thanks!
I'll make a new free account then, and let it know here how that pans out.

**Comment by bascurtiz** [comment]
@Essasetic 
You were right. Free account works. Thought quality is therefor not the best.
See comparison: https://i.imgur.com/aUPNn9m.png

**Comment by Essasetic** [comment]
> @Essasetic
> You were right. Free account works. Thought quality is therefor not the best.
> See comparison: https://i.imgur.com/aUPNn9m.png

Yeah, Spotify throttles it for free accounts iirc.

**Comment by meik97** [comment]
@Essasetic @bascurtiz 
Big thanks to both of you!

Hopefully this will fix the other crashes in #3 too.

**Comment by bascurtiz** [comment]
@meik97 
You're welcome!
Can you try to support Premium accounts too?
If needed, I can provide my acc. U on TG/Discord?

If you can find the location of the encrypted stream in 320kbps we could see if the same decryption method works. Using Wireshark and the official app or something like that.

**Comment by meik97** [comment]
@bascurtiz I will look into the premium issue.

You can join this discord: http://discord.gg/EByRp27

I will close this issue since the issue has been resolved for you.
