### ISSUE TITLE
Trojan:Win32/Zpevdo.A

### ISSUE THREAD

**Issue by dumbdumb** [meik97/XSpotify#9]
Windows defender detect XSpotify.exe as Trojan:Win32/Zpevdo.A

virustotal scan: https://www.virustotal.com/gui/file/5a57ba93d07ba7b7e2cb84f502993abc2958a5a79be2e0f9131d221c566e2c86/detection

**Comment by meik97** [comment]
Its a false-positive.

You can simply clone the repo and build it yourself if you want to be 100% sure.
